## 파일로딩
데이터가 없기 때문에 실제 코드는 문서에 있음
여기서는 np를 다루는 법만

In [4]:
import numpy as np
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(b[:, 1])
print(b[-1])
print(b[-1, :])
# :은 ...으로 대체 가능하다.
print(b[-1, ...])
print(b[0:2, :])

[ 2  6 10]
[ 9 10 11 12]
[ 9 10 11 12]
[ 9 10 11 12]
[[1 2 3 4]
 [5 6 7 8]]


## 로지스틱회귀

In [5]:
# 여기부터 강의를 따라가는 편의상 버전1을 사용한다.
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [7]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1], name='bias'))

In [8]:
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

In [9]:
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

In [16]:
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

In [17]:
# True if hypothesis > 0.5 else False 이를 tf.cast를 통해서 float32의 형태, 1.0과 0.0으로 바꿔줌
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [18]:
with tf.Session() as sess:
  # Initialize TensorFlow Variables
  sess.run(tf.global_variables_initializer())

  # 학습의 과정
  for step in range(10001):
    cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
    if step % 200 == 0:
      print(step, cost_val)

  # 정확성 확인
  h, c, a = sess.run([hypothesis, predicted, accuracy],
                     feed_dict={X: x_data, Y: y_data})
  print("\nHypothesis: ", h, "\nCorrect (Y): ", c, "\nAccuracy: ", a)

0 0.42993405
200 0.41033968
400 0.39665508
600 0.38369802
800 0.3714037
1000 0.35972473
1200 0.3486228
1400 0.33806455
1600 0.32801998
1800 0.31846082
2000 0.3093605
2200 0.300694
2400 0.29243717
2600 0.28456712
2800 0.27706227
3000 0.26990178
3200 0.26306638
3400 0.2565376
3600 0.250298
3800 0.2443314
4000 0.23862237
4200 0.23315649
4400 0.22792017
4600 0.22290075
4800 0.21808636
5000 0.21346577
5200 0.20902842
5400 0.20476466
5600 0.20066513
5800 0.19672127
6000 0.19292502
6200 0.18926866
6400 0.18574516
6600 0.18234771
6800 0.17907023
7000 0.17590652
7200 0.17285128
7400 0.16989915
7600 0.16704525
7800 0.16428508
8000 0.16161416
8200 0.15902841
8400 0.1565239
8600 0.15409712
8800 0.15174448
9000 0.14946279
9200 0.14724897
9400 0.14510018
9600 0.14301363
9800 0.1409866
10000 0.13901679

Hypothesis:  [[0.02645832]
 [0.1526024 ]
 [0.2836755 ]
 [0.7912375 ]
 [0.9456161 ]
 [0.9822153 ]] 
Correct (Y):  [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  1.0
