In [ ]:
import tensorflow as tf

In [24]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

W = tf.Variable(tf.random.normal([3, 1]), name='weight1')
print(W)
b = tf.Variable(tf.random.normal([1]), name='bias')

learning_rate = 1e-5
for i in range(100001):
  with tf.GradientTape() as tape:
    hypothesis = tf.matmul(x_data, W) + b
    cost = tf.reduce_mean(tf.square(hypothesis - y_data))

  W_grad, b_grad = tape.gradient(cost, [W, b])
  W.assign_sub(learning_rate * W_grad)
  b.assign_sub(learning_rate * b_grad)

 
print(hypothesis)
print("Step {:5} | Cost {:10.4f}".format(i, cost.numpy()))

<tf.Variable 'weight1:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.18990333],
       [ 0.5962388 ],
       [-1.034064  ]], dtype=float32)>
tf.Tensor(
[[151.558  ]
 [184.61983]
 [180.78114]
 [195.94391]
 [142.05042]], shape=(5, 1), dtype=float32)
Step 100000 | Cost     0.1912


In [88]:
print(tf.matmul([[80., 80., 100.]], W) + b)
print(tf.matmul([[73., 80., 75.]], W) + b)

tf.Tensor([[167.84416]], shape=(1, 1), dtype=float32)
tf.Tensor([[151.558]], shape=(1, 1), dtype=float32)


In [89]:
def hypothesis(X):
  return tf.matmul(X, W) + b

In [96]:
print(hypothesis([[80., 80., 100.]]))
print(hypothesis([[100., 70., 101.]]))
print(hypothesis([[60., 70., 110.]]))
print(hypothesis([[90., 100., 80.]]))

tf.Tensor([[167.84416]], shape=(1, 1), dtype=float32)
tf.Tensor([[185.13167]], shape=(1, 1), dtype=float32)
tf.Tensor([[143.0675]], shape=(1, 1), dtype=float32)
tf.Tensor([[183.58244]], shape=(1, 1), dtype=float32)
